Update patch set 2
Patch Set 2:

> I've seen two tests failing locally; investigating.

Two test failures on ARM:
* 449-checker-bce
* 530-checker-loops

These seem to be due to out-of-date Checker assertions:

  [ 59% 391/655] build test-art-target-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-picimage-npictest-ndebuggable-449-checker-bce32
  checker exit status: 1
  /ssd2/aosp-art/art/test/449-checker-bce: FAILED!
   
  #################### info
  # Checker test for testing array bounds check elimination.
  #################### diffs
  --- expected.txt	2016-02-23 16:14:44.140992945 +0000
  +++ output.txt	2016-11-03 16:22:29.434368833 +0000
  @@ -1,2 +1,4 @@
   JNI_OnLoad called
   java.lang.ArrayIndexOutOfBoundsException: length=5; index=82
  +error: Test case not found in the CFG file
  +Main.java:1415: void Main.partialLooping(int[], int, int) BCE (before)
  ####################
  
  449-checker-bce files deleted from host 
  and from target
  test-art-target-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-picimage-npictest-ndebuggable-449-checker-bce32 FAILED
  [ 74% 491/655] build test-art-target-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-picimage-npictest-ndebuggable-530-checker-loops232
  checker exit status: 1
  /ssd2/aosp-art/art/test/530-checker-loops2: FAILED!
   
  #################### info
  # Test on loop optimizations.
  #################### diffs
  --- expected.txt	2016-03-23 18:15:19.775885632 +0000
  +++ output.txt	2016-11-03 16:25:48.292562265 +0000
  @@ -1 +1,3 @@
   passed
  +error: Test case not found in the CFG file
  +Main.java:640: int Main.wrapAroundDynamicBCE(int[]) BCE (before)
  ####################
   
  530-checker-loops2 files deleted from host 
  and from target
  test-art-target-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-picimage-npictest-ndebuggable-530-checker-loops232 FAILED

I'll look into these tomorrow.

Patch-set: 2