Update patch set 8
Patch Set 8:

> FAIL: All checks failed. See below.
 > 
 > 
 > === aosp-master/aosp_arm64-eng ===
 > 
 > FAIL: Failed to build aosp-master/aosp_arm64-eng. See
 > https://android-build.googleplex.com/builds/pending/P3152929/aosp_arm64-eng/latest

  make -j80 PRODUCT-aosp_arm64-eng showcommands dist DIST_DIR=/buildbot/dist_dirs/aosp-master-linux-aosp_arm64-eng/P3152929/0 checkbuild
  FAILED: /bin/bash -c "(PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-3016494/bin/clang++ 	-I external/gtest/include -I external/icu/icu4c/source/common -I external/lz4/lib -I external/valgrind/include -I external/valgrind -I external/vixl/src -I external/zlib -I bionic/libc/private -I art/runtime -I art/disassembler -I art/compiler -I out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates -I out/host/linux-x86/gen/SHARED_LIBRARIES/libart-compiler_intermediates -I libnativehelper/include/nativehelper \$(cat out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/import_includes)   -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem out/host/linux-x86/obj/include -c  -fno-exceptions -Wno-multichar -Wa,--noexecstack -fPIC -no-canonical-prefixes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -O2 -g -fno-strict-aliasing --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8 --sysroot prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/sysroot -fstack-protector-strong -m64 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined   -target x86_64-linux-gnu -Bprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8 -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8/backward -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8/x86_64-linux  -Wthread-safety -Wthread-safety-negative -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-constant-conversion -Wno-undefined-var-template -Wmissing-noreturn -fno-rtti -std=gnu++11 -ggdb3 -Wall -Werror -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -DART_DEFAULT_GC_TYPE_IS_CMS -DIMT_SIZE=43 -fno-omit-frame-pointer -DART_BASE_ADDRESS=0x60000000 -DART_ENABLE_CODEGEN_arm -DART_ENABLE_CODEGEN_arm64 -DART_ENABLE_CODEGEN_mips -DART_ENABLE_CODEGEN_mips64 -DART_ENABLE_CODEGEN_x86 -DART_ENABLE_CODEGEN_x86_64 -DART_FRAME_SIZE_LIMIT=1736 -DART_STACK_OVERFLOW_GAP_arm=8192 -DART_STACK_OVERFLOW_GAP_arm64=8192 -DART_STACK_OVERFLOW_GAP_mips=16384 -DART_STACK_OVERFLOW_GAP_mips64=16384 -DART_STACK_OVERFLOW_GAP_x86=8192 -DART_STACK_OVERFLOW_GAP_x86_64=8192 -DART_BASE_ADDRESS_MIN_DELTA=-0x1000000 -DART_BASE_ADDRESS_MAX_DELTA=0x1000000 -O3 -Wframe-larger-than=1736 -fPIC -D_USING_LIBCXX -DANDROID_STRICT -std=gnu++14 -nostdinc++  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast  -Werror=address-of-temporary -Werror=return-type    -MD -MF out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.d -o out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.o art/compiler/optimizing/code_generator_x86.cc ) && (cp out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.d out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$//' -e '/^\$/ d' -e 's/\$/ :/' < out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.d >> out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.P; rm -f out/host/linux-x86/obj/SHARED_LIBRARIES/libart-compiler_intermediates/optimizing/code_generator_x86.d )"
  art/compiler/optimizing/code_generator_x86.cc:5413:95: error: too many arguments to function call, expected 5, have 6
                  instruction, temp_loc, array, class_offset, temp2_loc, /* needs_null_check */ true);
                                                                                                ^~~~
  art/compiler/optimizing/code_generator_x86.h:485:3: note: 'GenerateFieldLoadWithBakerReadBarrier' declared here
    void GenerateFieldLoadWithBakerReadBarrier(HInstruction* instruction,
    ^
  art/compiler/optimizing/code_generator_x86.cc:5421:84: error: too many arguments to function call, expected 5, have 6
                                                              /* needs_null_check */ false);
                                                                                     ^~~~~
  art/compiler/optimizing/code_generator_x86.h:485:3: note: 'GenerateFieldLoadWithBakerReadBarrier' declared here
    void GenerateFieldLoadWithBakerReadBarrier(HInstruction* instruction,
    ^
  art/compiler/optimizing/code_generator_x86.cc:5434:84: error: too many arguments to function call, expected 5, have 6
                                                              /* needs_null_check */ false);
                                                                                     ^~~~~
  art/compiler/optimizing/code_generator_x86.h:485:3: note: 'GenerateFieldLoadWithBakerReadBarrier' declared here
    void GenerateFieldLoadWithBakerReadBarrier(HInstruction* instruction,
    ^
  3 errors generated.

I probably need to rebase.

Patch-set: 8