Update patch set 6
Patch Set 6:

This broke arm64 builds:

art/dex2oat/dex2oat.cc:1554:1: error: the frame size of 1856 bytes is larger than 1728 bytes [-Werror=frame-larger-than=]

I'll revert.

Patch-set: 6
Reviewer: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0