Update patch set 1
Patch Set 1:

I am reverting this change due to a build break.

In file included from art/compiler/dex/type_inference_test.cc:26:
art/compiler/utils/test_dex_file_builder.h:219:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move(dex_file);
           ^
art/compiler/utils/test_dex_file_builder.h:219:12: note: remove std::move call here
    return std::move(dex_file);
           ^~~~~~~~~~        ~
1 error generated.

Patch-set: 1