Update patch set 1
Patch Set 1:

> > > > > > > > Would probably be worthwhile to clean up the ancient
 > > arm
 > > > > code
 > > > > > > > > that's using old syntax (some of which was written
 > back
 > > > in
 > > > > > > 2007).
 > > > > > > > > For reference, here's a clang bug report describing
 > the
 > > > > > issue:
 > > > > > > > >
 > > > > > > > > https://llvm.org/bugs/show_bug.cgi?id=24350
 > > > > > > > >
 > > > > > > > > I'll file a feature request against myself to update
 > > the
 > > > > old
 > > > > > > arm
 > > > > > > > > code, and we can back out the special case when that
 > > goes
 > > > > in.
 > > > > > > >
 > > > > > > > Interestingly, compiling for aosp_shamu, I get this:
 > > > > > > >
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:
 > Assembler
 > > > > > > messages:
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:4312:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r0,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:4348:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r2,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:5515:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r0,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:5550:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r2,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:6618:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r0,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:6652:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r2,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:6906:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r0,r0,r1'
 > > > > > > > art/runtime/interpreter/mterp/out/mterp_arm.S:6941:
 > > Error:
 > > > > > > selected
 > > > > > > > processor does not support ARM mode `sdiv r2,r0,r1'
 > > > > > > >
 > > > > > > > Are we not setting the right flags?
 > > > > > >
 > > > > > > (For our arm32 assembler test, I had to use
 > "-march=armv7-a
 > > > > > > -mcpu=cortex-a15" to get sdiv. Seems we're pushing
 > > > > > -mcpu=cortex-a15
 > > > > > > -mcpu=krait, but I can't find march.)
 > > > > >
 > > > > > I'm testing whether we should add these directives (we use
 > > for
 > > > > the
 > > > > > other assembly files):
 > > > > >
 > > > > > .arch armv7-a
 > > > > > .thumb
 > > > >
 > > > > OK, it isn't thumb code, so can't use .thumb.
 > > >
 > > > Doesn't work. :-(
 > >
 > > It seems the issue is mcpu=krait. It's not passed to as, as gcc
 > > doesn't seem to know it. What I get:
 > >
 > > "prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/as"
 > > -mfloat-abi=softfp -march=armv7-a -mfpu=neon-vfpv4 -I
 > > external/gtest/include -I external/icu/icu4c/source/common -I
 > > external/lz4/lib -I external/valgrind/include -I
 > external/valgrind
 > > -I external/vixl/src -I external/zlib -I bionic/libc/private -I
 > > art/cmdline -I art/sigchainlib -I art -I art/runtime -I
 > > /ssd3/builds/aosp/hh/aosp-master/target/product/shamu/obj/SHARED_LIBRARIES/libart_intermediates
 > > -I /ssd3/builds/aosp/hh/aosp-master/target/product/shamu/gen/SHARED_LIBRARIES/libart_intermediates
 > > -I libnativehelper/include/nativehelper -I system/core/libnativeloader/include
 > > -I external/lz4/lib -I external/libcxx/include -I
 > external/libcxxabi/include
 > > -I external/zlib -I system/core/base/include --noexecstack -o
 > > /ssd3/builds/aosp/hh/aosp-master/target/product/shamu/obj/SHARED_LIBRARIES/libart_intermediates/interpreter/mterp/out/mterp_arm.o
 > > /tmp/mterp_arm-db8e65.s
 > >
 > > If I add -mcpu=krait, I get:
 > >
 > > Error: unknown cpu `krait'
 > >
 > > If I add -mcpu=cortex-a15, it works.
 > 
 > When using the Clang integrated assembler, on the other hand, Clang
 > passes down "-target-cpu krait," which probably is what makes this
 > work.
 > 
 > Gotta check what GCC passes down.

(I think this is because we only add -mcpu=krait in the build if we're building with Clang.)

Patch-set: 1