Update patch set 1
Patch Set 1:

> Makes sense. Does this mean that if I want to flip bits of a short,
 > i must do neg-int and then cast back with int-to-short to type
 > correctly? I don't suppose we have a spec for this but do you know
 > what the verifier does?

Yes, otherwise for:

    byte[] a = new byte[32];
    return ~a[1];


You get:

Foo.java:8: error: possible loss of precision
    return ~a[1];
           ^
  required: short
  found:    int
1 error
1 warning

So you need to do the explicit cast.

Patch-set: 1