Update patch set 3
Patch Set 3:

I think the read barrier config build broke:

art/runtime/lambda/closure_builder.cc:48:68: error: function 'CaptureVariableObject' could be declared with attribute 'noreturn' [-Werror,-Wmissing-noreturn]

Patch-set: 3
Reviewer: Hiroshi Yamauchi <1022530@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0