Update patch set 1
Patch Set 1:

Nicolas: sorry, I pushed the patch to the wrong Gerrit, we will test it on our private Gerrit first.

We are seeing various interleaved message patterns in any configuration (Quick/Optimizing/interpreter), for instance:

--- expected.txt	2015-12-09 08:13:50.583294910 +0000
+++ output.txt	2015-12-09 08:55:35.635185771 +0000
@@ -1,15 +1,15 @@
 Got an NPE: second throw
 java.lang.NullPointerException: second throw
-	at Main.catchAndRethrow(Main.java:77)
+Static Init
+BadError: This is bad by convention: BadInit
+java.lang.NoClassDefFoundError: BadInit	at Main.catchAndRethrow(Main.java:77)
 	at Main.exceptions_007(Main.java:59)
 	at Main.main(Main.java:67)
 Caused by: java.lang.NullPointerException: first throw
 	at Main.throwNullPointerException(Main.java:84)
 	at Main.catchAndRethrow(Main.java:74)
 	... 2 more
-Static Init
-BadError: This is bad by convention: BadInit
-java.lang.NoClassDefFoundError: BadInit
+
 BadError: This is bad by convention: BadInit
 Static BadInitNoStringInit
 BadErrorNoStringInit: This is bad by convention

Patch-set: 1
Label: Verified=0